### ISSUE TITLE
Projection with nullable reference types doesn't work after upgrade to 4.2.0

### ISSUE THREAD

**Issue by WolfspiritM** [riok/mapperly#1796]
**Describe the bug**
After upgrading to 4.2.0 a projection that uses nullable value types and a custom (inlined) "Use" method doesn't seem to work correctly anymore.

**Declaration code**
```cs
[Mapper]
public static partial class TestMapper
{
    public static partial IQueryable<TestDto> ProjectToTestDto(this IQueryable<Test> query);

    [MapProperty(nameof(Test.Something), nameof(TestDto.Something), Use = nameof(MapSomething))]
    private static partial TestDto MapTest(Test test);

    [UserMapping(Default = false)]
    private static decimal MapSomething(decimal? something) => something ?? 0;

}

public class Test
{
    public decimal? Something { get; set; }
}

public class TestDto
{
    public decimal Something { get; set; }
}
```

**Actual relevant generated code**
Code from 4.2.0:
```csharp
new global::TestDto()
          {
              Something = x.Something != null ? x.Something.Value ?? 0 : default,
          }
```

**Expected relevant generated code**
Code from 4.1.1:
```csharp
new global::TestDto()
            {
                Something = x.Something ?? 0,
            }
```

**Reported relevant diagnostics**
Actual c# error:
* CS0019: Operator '??' cannot be applied to operands of type 'decimal' and 'int'

**Environment (please complete the following information):**
- Mapperly Version: [e.g. 1.0.1] 4.2.0
- Nullable reference types: enabled
- .NET Version: 9.0.4
- Target Framework: net9.0
- Compiler Version:  '4.13.0-3.25167.3 (73eff2b5)'. Language version: 13.0.
- C# Language Version: 13.0
- IDE: VS 17.13.6
- OS: Windows 11

**Comment by isak1080** [comment]
I have the exact same problem, but my code looks slightly different

This is the relevant converter method:

```
private static bool ConvertToIsPublic(Guid? instructorGuid) => instructorGuid == null;
```

and here is the relevant part of the generated `ProjectToDto` code:

```
IsPublic = x.InstructorGUID != null ? x.InstructorGUID.Value == null : default,
```

This runs, but obviously produce the wrong result (`IsPublic` is always false). Luckily my integration tests caught this before I published the code to production

**Comment by WolfspiritM** [comment]
@latonz Can you take a look again? The initial bug seems to work now but if mapping from "decimal?" to "decimal?" with a custom method doesn't work.

Just changing:
```cs
private static decimal MapSomething(decimal? something) => something ?? 0;
```
to
```cs
private static decimal? MapSomething(decimal? something) => something ?? 0;
```

Makes it fail in a very strange way:
```cs
    [global::System.CodeDom.Compiler.GeneratedCode("Riok.Mapperly", "4.2.1.0")]
    public static partial global::System.Linq.IQueryable<global::TestDto> ProjectToTestDto(this global::System.Linq.IQueryable<global::Test> query)
    {
#nullable disable
        return global::System.Linq.Queryable.Select(
            query,
            x => new global::TestDto()
            {
                Something = x.Something ?? 0 == null ? default : x.Something ?? 0.Value,
            }
        );
#nullable enable
    }
```

If then changing TestDto's Something to "decimal?" it still fails:

```cs
    [global::System.CodeDom.Compiler.GeneratedCode("Riok.Mapperly", "4.2.1.0")]
    public static partial global::System.Linq.IQueryable<global::TestDto> ProjectToTestDto(this global::System.Linq.IQueryable<global::Test> query)
    {
#nullable disable
        return global::System.Linq.Queryable.Select(
            query,
            x => new global::TestDto()
            {
                Something = x.Something != null ? x.Something.Value ?? 0 : default(decimal?),
            }
        );
#nullable enable
    }
```


I also think that something like this should work but it doesn't at the moment:

```cs
var t = new List<Test>()
{
	new Test()
	{
		Something = null
	}
}.AsQueryable();

var testDto = t.ProjectToTestDto();
Console.WriteLine(testDto.First().Something);



[Mapper]
public static partial class TestMapper
{
	public static partial IQueryable<TestDto> ProjectToTestDto(this IQueryable<Test> query);

	[MapProperty(nameof(Test.Something), nameof(TestDto.Something), Use = nameof(MapSomething))]
	private static partial TestDto MapTest(Test test);

	[UserMapping(Default = false)]
	private static decimal MapSomething(decimal? something) => something ?? 1;

}

public class Test
{
	public decimal? Something { get; set; }
}

public class TestDto
{
	public decimal? Something { get; set; }
}
```

This returns null instead of 1. Even so I told the mapper to use MapSomething for mapping. It works if MapSomething returns "decimal?" instead of decimal.

The generated code looks like this:

```cs
    [global::System.CodeDom.Compiler.GeneratedCode("Riok.Mapperly", "4.2.1.0")]
    public static partial global::System.Linq.IQueryable<global::TestDto> ProjectToTestDto(this global::System.Linq.IQueryable<global::Test> query)
    {
#nullable disable
        return global::System.Linq.Queryable.Select(
            query,
            x => new global::TestDto()
            {
                Something = x.Something != null ? (decimal?)x.Something.Value ?? 1 : default(decimal?),
            }
        );
#nullable enable
    }
```

**Comment by WolfspiritM** [comment]
@latonz Sure! Does this help?


Case 1: Mapping from decimal? to decimal? with correct types
```cs
[Fact]
public Task UserImplementedAttributedNullableValueTypeToNonNullable()
{
    var source = TestSourceBuilder.MapperWithBodyAndTypes(
        """
        public static partial IQueryable<B> Map(this IQueryable<A> query);

        [MapProperty(nameof(A.Value), nameof(B.Value), Use = nameof(MapValue))]
        private static partial B Map(A src);

        [UserMapping(Default = false)]
        private static decimal? MapValue(decimal? value) => value ?? 1;
        """,
        "public class A { public decimal? Value { get; set; } }",
        "public class B { public decimal? Value { get; set; } }"
    );

    return TestHelper.VerifyGenerator(source);
}
```

```cs
//HintName: Mapper.g.cs
// <auto-generated />
#nullable enable
public partial class Mapper
{
    [global::System.CodeDom.Compiler.GeneratedCode("Riok.Mapperly", "0.0.1.0")]
    public static partial global::System.Linq.IQueryable<global::B> Map(this global::System.Linq.IQueryable<global::A> query)
    {
#nullable disable
        return global::System.Linq.Queryable.Select(
            query,
            x => new global::B()
            {
                Value = x.Value != null ? x.Value.Value ?? 1 : default(decimal?),
            }
        );
#nullable enable
    }

    [global::System.CodeDom.Compiler.GeneratedCode("Riok.Mapperly", "0.0.1.0")]
    private static partial global::B Map(global::A src)
    {
        var target = new global::B();
        target.Value = MapValue(src.Value);
        return target;
    }
}
```
```x.Value != null ? x.Value.Value ?? 1 : default(decimal?)``` is not right. 



Case 2: Mapping from decimal? to decimal (even so target is decimal?)

```cs
    // test code
    [Fact]
    public Task UserImplementedAttributedNullableValueTypeToNonNullable()
    {
        var source = TestSourceBuilder.MapperWithBodyAndTypes(
            """
            public static partial IQueryable<B> Map(this IQueryable<A> query);

            [MapProperty(nameof(A.Value), nameof(B.Value), Use = nameof(MapValue))]
            private static partial B Map(A src);

            [UserMapping(Default = false)]
            private static decimal MapValue(decimal? value) => value ?? 1;
            """,
            "public class A { public decimal? Value { get; set; } }",
            "public class B { public decimal? Value { get; set; } }"
        );

        return TestHelper.VerifyGenerator(source);
    }
```

```cs
//HintName: Mapper.g.cs
// <auto-generated />
#nullable enable
public partial class Mapper
{
    [global::System.CodeDom.Compiler.GeneratedCode("Riok.Mapperly", "0.0.1.0")]
    public static partial global::System.Linq.IQueryable<global::B> Map(this global::System.Linq.IQueryable<global::A> query)
    {
#nullable disable
        return global::System.Linq.Queryable.Select(
            query,
            x => new global::B()
            {
                Value = x.Value != null ? (decimal?)x.Value.Value ?? 1 : default(decimal?),
            }
        );
#nullable enable
    }

    [global::System.CodeDom.Compiler.GeneratedCode("Riok.Mapperly", "0.0.1.0")]
    private static partial global::B Map(global::A src)
    {
        var target = new global::B();
        target.Value = (decimal?)MapValue(src.Value);
        return target;
    }
}
```

This is dangerous (even so it does even emit warnings for RMG073 it seems) as it does compile but if value is null in A the target value in B will be set to default(decimal?) (0) instead of 1 which makes the mapping method useless.
